### ISSUE TITLE
Add Packet filter in CheckConfig itself

### ISSUE THREAD

**Issue by Vivek-anand-jain** [gnandita/Implementation-of-CHOKe-in-ns3#4]
In the current implementation, you are adding filters in example and test. But this should be the implicit behaviour of Queue disc algorithm. You can add filter in CheckConfig method.

**Comment by Vivek-anand-jain** [comment]
Add Filter over here:
https://github.com/gnandita/Implementation-of-CHOKe-in-ns3/blob/95a7391e8d60250baa83dfe94aee406f0e77e56c/src/traffic-control/model/choke-queue-disc.cc#L637

**Comment by gnandita** [comment]
Added packet-filter in CheckConfig method.
