### ISSUE TITLE
This should be boolean variable

### ISSUE THREAD

**Issue by Vivek-anand-jain** [gnandita/Implementation-of-CHOKe-in-ns3#5]
https://github.com/gnandita/Implementation-of-CHOKe-in-ns3/blob/95a7391e8d60250baa83dfe94aee406f0e77e56c/src/traffic-control/model/choke-queue-disc.h#L242

**Comment by gnandita** [comment]
Changed the datatype of m_idle to bool in commit Resolving m_idletime issue
