### ISSUE TITLE
DoDequeue of CHOKe is implemented incorrectly

### ISSUE THREAD

**Issue by Vivek-anand-jain** [gnandita/Implementation-of-CHOKe-in-ns3#6]
- m_idleTime is getting updated every time DoDequeue is called even it was idle before.
 - If a queue has only one packet, it doesn't mark queue as idle after Dequeuing that packet.

https://github.com/gnandita/Implementation-of-CHOKe-in-ns3/blob/95a7391e8d60250baa83dfe94aee406f0e77e56c/src/traffic-control/model/choke-queue-disc.cc#L583

**Comment by gnandita** [comment]
Modified the code to check for empty queue after packet dequeue.
