### ISSUE TITLE
[Possible RED Bug] m_stats.forcedMark variable may conflict m_stats.qLimDrop and result into incorrect stat count.

### ISSUE THREAD

**Issue by Vivek-anand-jain** [gnandita/Implementation-of-CHOKe-in-ns3#8]
https://github.com/gnandita/Implementation-of-CHOKe-in-ns3/blob/95a7391e8d60250baa83dfe94aee406f0e77e56c/src/traffic-control/model/choke-queue-disc.cc#L313

**Comment by gnandita** [comment]
Modified the code to resolve the conflict.
